### ISSUE TITLE
Could not find a version that satisfies the requirement apex==0.1 

### ISSUE THREAD

**Issue by yangzhch6** [vmurahari3/visdial-bert#1]
I got the following error:

> ERROR: Could not find a version that satisfies the requirement apex==0.1 (from -r /media/data1/YZC_visdial-bert/visdial-bert/condaenv.abp1qb3g.requirements.txt (line 2)) (from versions: 0.9.8dev.linux-i686, 0.9.8.dev0, 0.9.8a0.dev0, 0.9.9.dev0, 0.9.10.dev0)
ERROR: No matching distribution found for apex==0.1 (from -r /media/data1/YZC_visdial-bert/visdial-bert/condaenv.abp1qb3g.requirements.txt (line 2))

My machine has 8 GTX2080Ti. I've had apex installation problems before on the ViLBERT project, but not like this one. Have you ever meet this error? What is your GPU?
I would be appreciate if you can help me.

**Comment by vmurahari3** [comment]
My apologies for the late response on this. The apex package is not needed for this code. This is an error on my end. I have pushed a new env.yml file. Please let me know if that does it for you.
