### ISSUE TITLE
Question about the rcnn boxes

### ISSUE THREAD

**Issue by AmeenAli** [vmurahari3/visdial-bert#10]
Hello,
I am confused a little bit about the following : 
in : https://github.com/vmurahari3/visdial-bert/blob/master/dataloader/dataloader_visdial.py#L241
in the line : 
`features, num_boxes, boxes, _ , image_target = self._image_features_reader[img_id]`

the shape of boxes is [37 x 5] , what does the 5 values mean? I expected it to be a 4 coordinates indicating x1 , x2 , y1 , y2 , can you clarify? thanks!

**Comment by vmurahari3** [comment]
5th value is the percentage of the area of the rectangular box in the image i.e area of image / (x1 - x2) (y1 - y2). For more details, check out the ViLBERT paper and the following code repository https://github.com/jiasenlu/vilbert_beta.
