### ISSUE TITLE
The length of train and val.

### ISSUE THREAD

**Issue by simpleshinobu** [vmurahari3/visdial-bert#4]
In your processed data, the training length is 123187 and the validation length is 2060. When I download the original text data from the visdial website, I find the length are 123287 and 2064 respectively. What is the reason.

**Comment by vmurahari3** [comment]
The preprocessing script (https://github.com/vmurahari3/visdial-bert/blob/master/preprocessing/pre_process_visdial.py) removes instances where the total length of the dialog sequences exceeds the maximum length, which is supplied as an argument. The provided processed data was derived by running this script with a maximum length of 256.

**Comment by simpleshinobu** [comment]
Thank you for your response!

**Comment by gicheonkang** [comment]
Hi, @vmurahari3 

Thank you for releasing the source code.

I would like to check the performance of the visdial-bert in EvalAI server, but the server requires the json submission format as pre-defined length (train:123287, val:2064).

Could you recommend any method that I can check the performance of your model in EvalAI?
