### ISSUE TITLE
The question about training base model

### ISSUE THREAD

**Issue by simpleshinobu** [vmurahari3/visdial-bert#5]
Following the default setting, when I tarin the baseline model, after 50000~iterations(about 18 epochs), I find I only get ~0.65MRR and ~0.58NDCG. Have I missed something?

**Comment by vmurahari3** [comment]
I think with a batch size of 80, an epoch is around 10K iterations. Could you please check if you trained for 18 epochs?

**Comment by simpleshinobu** [comment]
OK, Thanks. So, could you tell me how many iterations can nearly reach your results.

**Comment by vmurahari3** [comment]
I would say around 200K to 300K iterations would be good enough.
