### ISSUE TITLE
I am quite confused about the next_sentence_label. 

### ISSUE THREAD

**Issue by Mingxiao-Li** [vmurahari3/visdial-bert#6]
Why here labeled 1 for negative samples and 0 for positive samples ? Based on my understanding, this model uses crossentropy loss and the aim is to maximize the probability of seeing correct answer appended to the input text, then 1 should be labeled for positive samples and 0 for negative samples, right ?

**Comment by vmurahari3** [comment]
We use the following transformer implementation https://github.com/huggingface/transformers and the labels are consistent with the implementation.

Regarding the CE calculations, look at https://github.com/huggingface/transformers/blob/cafa6a9e29f3e99c67a1028f8ca779d439bc0689/src/transformers/modeling_bert.py#L498 and https://github.com/huggingface/transformers/blob/cafa6a9e29f3e99c67a1028f8ca779d439bc0689/src/transformers/modeling_bert.py#L844
