### ISSUE TITLE
Performance check in EvalAI

### ISSUE THREAD

**Issue by gicheonkang** [vmurahari3/visdial-bert#8]
Hi, @vmurahari3 @abhshkdz 

Thank you for releasing the source code.

I would like to check the validation performance of the visdial-bert in EvalAI server. 

Required length for the submission file is 2064 (validation), but visdial-bert returns only 2060 entries due to the max_seq_len=256 argument.

Could you recommend any method that I can check the validation performance of your model in EvalAI?

_Originally posted by @gicheonkang in https://github.com/vmurahari3/visdial-bert/issues/4#issuecomment-686363787_

**Comment by vmurahari3** [comment]
Hello, For submitting the validation prediction to the EvalAI servers, we randomly selected answers for the remaining 4 samples.

**Comment by gicheonkang** [comment]
thank you!

**Comment by gicheonkang** [comment]
Thank you!
